name: pipeline
 
on:
  push:
    branches: [ main, develop, sonar ]

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
 
    - name: Build and test with Maven
      run: mvn clean verify sonar:sonar
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
    - name: Upload JaCoCo Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/index.html
 
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packaged-jars
        path: target/*.jar
